### ISSUE TITLE
Env conflict

### ISSUE THREAD

**Issue by Mahmoudgalalz** [Nutlope/aicommits#1]
I do use the Open ai key with the same variable name, so could we change the default name of it I can do it, It will be more good reason cuz most of the users are devs 😂

**Comment by Nutlope** [comment]
Good point! Yeah let's maybe change it to OPENAI_KEY and also keep the other one as a fall back? Feel free to submit a PR @Mahmoudgalalz :)

**Comment by Nutlope** [comment]
This is now done, thanks to @iamshabell for the PR!

**Comment by Mahmoudgalalz** [comment]
I will send the pr rn, I have done with it

**Comment by Mahmoudgalalz** [comment]
too late to send the pr, thanks @iamshabell
