### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by bdzanko17** [Nutlope/aicommits#112]
Hello all, I am trying this package but getting an internal server error. 

<img width="585" alt="image" src="https://user-images.githubusercontent.com/41085720/221022430-06c7beb9-b919-4f44-86f3-b119225765db.png">

**Comment by KennethLG** [comment]
I am getting the same error, it seems to be a new error, yesterday it was working fine.
<img width="478" alt="image" src="https://user-images.githubusercontent.com/64232342/221023967-3e78dfa8-2356-4813-87a9-2ca36b6913a9.png">

**Comment by llegomark** [comment]
Outage on multiple models: https://status.openai.com/incidents/s29fb94kx5q7

**Comment by bdzanko17** [comment]
Thanks guys, working now :)
