### ISSUE TITLE
Add the aicommits recommended text to the commit description not its message

### ISSUE THREAD

**Issue by ibnsamy96** [Nutlope/aicommits#116]
I found aicommits a great example of how chatgpt can be used to help developers automate their tasks. I just think the recommended messages it gave are out of context, the package doesn't know what project I'm working on, what feature I'm developing, and why I'm writing this code that way, so it gives simple commit messages as "Added function X instead of function Y" which is great as a commit description not as a message.
I'm suggesting another approach, the developer should still the commit message writer (to make sure that the commit message relates to the project context) and chatgpt writes the commit description (to make sure that much details were written). This way, developers of the same team will understand each other easily as each of their commits will have enough info about the difference it makes to the product.
I hope you can test my approach in another version of your package, actually it could be offered as a paid feature for teams.
Good luck ^^

**Comment by privatenumber** [comment]
Most devs don't fill out or read commit details nowadays.

I think the dev needing to write a commit message summary kind of defeats the point of this tool.

Thanks for your idea though.
