### ISSUE TITLE
.aicommits file does not instantiate on `config set` command

### ISSUE THREAD

**Issue by bennnym** [Nutlope/aicommits#117]
<img width="958" alt="Screen Shot 2023-02-27 at 8 15 31 am 1" src="https://user-images.githubusercontent.com/46942903/221437818-e0fddb6c-2b44-4071-83fa-27c1ee53d5f6.png">

Unable to set this up :(

**Comment by privatenumber** [comment]
Sorry, the config command isn't released yet. It's ready to go but waiting on the publisher to update the authentication token. Hopefully released in a few days.

**Comment by FrankKai** [comment]
+1

**Comment by law-chain-hot** [comment]
Here is a way to solve it. @FrankKai @bennnym 

You guys could directly touch a file `.aicommit` in `~/.aicommit` with the following code

```bash
OPENAI_KEY = "<Your code>"
```


Because it parse the string by `ini.parse`
https://github.com/Nutlope/aicommits/blob/2041aee003aec7453cc204676f2b358c3b020eeb/src/utils/config.ts#L50-L51

**Comment by FrankKai** [comment]
> Here is a way to solve it. @FrankKai @bennnym
> 
> You guys could directly touch a file `.aicommit` in `~/.aicommit` with the following code
> 
> ```shell
> OPENAI_KEY = "<Your code>"
> ```
> 
> Because it parse the string by `ini.parse`
> 
> https://github.com/Nutlope/aicommits/blob/2041aee003aec7453cc204676f2b358c3b020eeb/src/utils/config.ts#L50-L51

It works. Thank you very much!

**Comment by privatenumber** [comment]
`config` command released in https://github.com/Nutlope/aicommits/releases/tag/v1.2.0
