### ISSUE TITLE
Cannot read property 'statusText' of undefined

### ISSUE THREAD

**Issue by kityeungfe** [Nutlope/aicommits#122]
Window 10 system
![image](https://user-images.githubusercontent.com/111792923/222361939-ad298322-cab6-4c2c-81ee-c8c956fa1b5b.png)

**Comment by privatenumber** [comment]
What version are you using?

**Comment by privatenumber** [comment]
We no longer have any references to `statusText` so this must be from v1.1.0:
https://github.com/Nutlope/aicommits/blob/68fc8ad736e38a9497e94236800d32c9264576d7/src/utils.ts#L98

Please try the latest release: https://github.com/Nutlope/aicommits/releases/tag/v1.2.0

**Comment by M09Ic** [comment]
The bug does not seem to have disappeared in version 1.2 either.

![image](https://user-images.githubusercontent.com/29176200/222628420-bf7901e7-e2b5-49e2-bfda-135a531771f6.png)

**Comment by privatenumber** [comment]
Hopefully this fixes it: https://github.com/Nutlope/aicommits/pull/106
I also added this: https://github.com/Nutlope/aicommits/pull/124 which should improve debugging

**Comment by privatenumber** [comment]
Closing this for now but let me know if it's still an issue and we can re-open it.
