### ISSUE TITLE
read ECONNRESET

### ISSUE THREAD

**Issue by xiaojun0901** [Nutlope/aicommits#125]
### Bug description

 The AI is analyzing your changes   

└  ✖ read ECONNRESET

    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)

    aicommits v1.3.0

### aicommits version

v1.3.0

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 81.37 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.1 - /usr/local/opt/node@14/bin/node
    npm: 6.14.17 - /usr/local/opt/node@14/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Does this happen consistently for you?

I wonder if all we need is an error handling to ignore the error:
https://stackoverflow.com/questions/53912439/nodejs-econnreset

Please try using the [latest Node v14 (v14.21.3)](https://nodejs.org/download/release/latest-v14.x/).

**Comment by privatenumber** [comment]
Closing in favor of https://github.com/Nutlope/aicommits/issues/136

Let's discuss there
