### ISSUE TITLE
 Du[n] is not a function

### ISSUE THREAD

**Issue by mahmoudkandeel** [Nutlope/aicommits#126]
### Bug description

└  ✖ Du[n] is not a function

    at he (file:///C:/Users/Mahmoud/AppData/Roaming/npm/node_modules/aicommits/dist/cli.mjs:61:2965)
    at async file:///C:/Users/Mahmoud/AppData/Roaming/npm/node_modules/aicommits/dist/cli.mjs:64:15

    aicommits v1.3.0

### aicommits version

1.3.0

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 26.82 GB / 39.37 GB
  Binaries:
    Node: 14.21.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.18 - C:\Program Files\nodejs\npm.CMD
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Maps to this line:
https://github.com/Nutlope/aicommits/blob/5fe127d377eeeec8ba08dd4a0052ec5e5272fe14/src/utils/config.ts#LL54C18-L54C31

Will fix on our end but I think you have an invalid config property in `~/.aicommits`.

**Comment by mahmoudkandeel** [comment]
@privatenumber thanks for response, yes it was an issue for config file, so i removed it and rerun `aicommits config set OPENAI_KEY=<your token>` and it works as expected

**Comment by privatenumber** [comment]
Glad that fixed it.
Will keep this open until the error is handled.
