### ISSUE TITLE
OpenAI key length check is invalid

### ISSUE THREAD

**Issue by salomartin** [Nutlope/aicommits#127]
### Bug description

There are OpenAI keys that are shorter than 51 and work perfectly fine. I have one that's 43 characters long and works perfectly fine.

### aicommits version

v1.3.0

### Environment

```shell
*
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Thanks,

Do you know if they document the spec for API key (e.g. length, characters)?

We should consider removing the length check if not.

**Comment by salomartin** [comment]
Did a 10 min light search, couldn't find any spec. Out of curiosity, I created a new key, and that was longer than 51, so there doesn't seem to be a fixed standard per se. I think checking the prefix may be enough to sense check and avoid any missing or empty variables.
