### ISSUE TITLE
Excluding a file/path

### ISSUE THREAD

**Issue by ab2pentest** [Nutlope/aicommits#128]
### Feature request

Adding a flag like `-x="filename"` and this filename or path will be excluded

![image](https://user-images.githubusercontent.com/84577967/222778316-74fdf31b-3bb8-4218-9dcb-d44403409b86.png)

### Why?

I have a large file where I don't need to check changes on it, so is it possible to add a flag where I can exclude a file or bunch of files.

**Comment by privatenumber** [comment]
PR welcome!
