### ISSUE TITLE
Hostname/IP does not match certificate's altnames

### ISSUE THREAD

**Issue by zhouyijiaren** [Nutlope/aicommits#135]
### Bug description

The AI is analyzing your changes   
│
└  ✖ Hostname/IP does not match certificate's altnames: Host: api.openai.com. is not in the cert's altnames: DNS:*.facebook.com, DNS:*.facebook.net, DNS:*.fbcdn.net, DNS:*.fbsbx.com, DNS:*.m.facebook.com, DNS:*.messenger.com, DNS:*.xx.fbcdn.net, DNS:*.xy.fbcdn.net, DNS:*.xz.fbcdn.net, DNS:facebook.com, DNS:messenger.com

    at Object.checkServerIdentity (tls.js:297:12)
    at TLSSocket.onConnectSecure (_tls_wrap.js:1507:27)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

    aicommits v1.3.0

    Please open a Bug report with the information above:

### aicommits version

v1.3.0

### Environment

```shell
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 29.16 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.13.2 - /usr/local/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
It looks like you're using an invalid SSL certificate.

Are you behind a VPN?

Please try using the [latest Node.js v14 (v14.21.3)](https://nodejs.org/download/release/latest-v14.x/).

**Comment by zhouyijiaren** [comment]
I can get the analyzed ANSWER now! I don't do anything. Just restart the computer, and switch the VPN. Thank you for your attention.
