### ISSUE TITLE
OpenAI API Error: 400 - Bad Request

### ISSUE THREAD

**Issue by edu-hilario** [Nutlope/aicommits#137]
### Bug description

![image](https://user-images.githubusercontent.com/48762158/223226193-dd07d1b2-da76-4c82-b982-df2b082965d9.png)
`OpenAI API Error: 400 - Bad Request`

This one started to happen as soon as I updated from `1.2.0` to `1.3.0`. It is a weird one because it happens some of the times, but not always, so reproducing it is just luck. I even changed the API key, but that doesn't seem to be the issue.

### aicommits version

v1.3.0

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 42.57 GB / 63.83 GB
    Shell: PowerShell 7.3.3
  Binaries:
    Node: 14.21.2 - C:\Program Files\nodejs\node.EXE    
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD      
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Hmm it's a server-side error so it could be a problem with OpenAI.

Perhaps it's because we changed the way we count tokens: https://community.openai.com/t/error-retrieving-completions-400-bad-request/34004/6

Are your diffs really large?

**Comment by edu-hilario** [comment]
> Hmm it's a server-side error so it could be a problem with OpenAI.
> 
> Perhaps it's because we changed the way we count tokens: https://community.openai.com/t/error-retrieving-completions-400-bad-request/34004/6
> 
> Are your diffs really large?

No, not really, the size of the diff doesn't make a difference, the error occur on small and big diffs.

**Comment by privatenumber** [comment]
Can you provide it?

I can't do much with how little information is provided right now.

**Comment by Mobilpadde** [comment]
Just chiming in, I'm getting `404`s all the time :shrug:

**Comment by mahamaad** [comment]
i have same issue

**Comment by gabrielmoris** [comment]
> I have exactly the same Problem, but I always get this 400 Error.

EDIT: after > `npm update -g aicommits `problem Solved

**Comment by privatenumber** [comment]
@Mobilpadde 404 is a completely different error and a more problematic one. It means the server you're reaching is returning a "Not found". Do you have some sort of network configuration (e.g. VPN)?

For anyone else experiencing a 400 error, an example if the diff you're sending would be _very_ helpful so I can reproduce the problem on my end.

**Comment by mael-queau** [comment]
> @Mobilpadde 404 is a completely different error and a more problematic one. It means the server you're reaching is returning a "Not found". Do you have some sort of network configuration (e.g. VPN)?
> 
> For anyone else experiencing a 400 error, an example if the diff you're sending would be _very_ helpful so I can reproduce the problem on my end.

Here, I am consistently experiencing 400's on anything I try to generate a commit name for, but here is the first one for which it occurred:

```diff
diff --git a/tracabilite.ipynb b/tracabilite.ipynb
new file mode 100644
index 0000000..6301d1f
--- /dev/null
+++ b/tracabilite.ipynb
@@ -0,0 +1,121 @@
+{
+ "cells": [
+  {
+   "cell_type": "markdown",
+   "source": [
+    "# Script utilitaire pour la traçabilité des contenants Berny"
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  },
+  {
+   "cell_type": "code",
+   "execution_count": 30,
+   "outputs": [],
+   "source": [
+    "file_items = \"export_public_Item_2023_03_08_16_03_42_201.csv\"\n",
+    "file_cleaning = \"export_public_Cleaning_2023_03_08_16_43_10_595.csv\"\n",
+    "file_delivery = \"export_public_Delivery_2023_03_08_16_43_24_349.csv\"\n",
+    "file_returns = \"export_public_Delivery_back_2023_03_08_16_43_32_493.csv\""
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  },
+  {
+   "cell_type": "code",
+   "execution_count": 31,
+   "outputs": [],
+   "source": [
+    "import csv\n",
+    "import pandas as pd\n",
+    "import numpy as np\n",
+    "import matplotlib.pyplot as plt\n",
+    "\n",
+    "items = pd.read_csv(file_items, sep=\",\", encoding=\"utf-8\")\n",
+    "cleanings = pd.read_csv(file_cleaning, sep=\",\", encoding=\"utf-8\")\n",
+    "deliveries = pd.read_csv(file_delivery, sep=\",\", encoding=\"utf-8\")\n",
+    "returns = pd.read_csv(file_returns, sep=\",\", encoding=\"utf-8\")"
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  },
+  {
+   "cell_type": "markdown",
+   "source": [
+    "Items: ['id', 'size', 'arrival_date', 'arrival_country', 'in_transit', 'type', 'is_defunct']\n",
+    "Cleanings: ['item_id', 'created_date', 'cleaning_date', 'cleaner', 'id']\n",
+    "Deliveries: ['item_id', 'transportedIn', 'createdDate', 'delivery_date', 'id', 'shop']\n",
+    "Returns: ['is_notified', 'is_unsold', 'actor', 'item_id', 'date', 'lot', 'id', 'shop']"
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  },
+  {
+   "cell_type": "markdown",
+   "source": [
+    "# 1. Quels sont les contenants qui ont été utilisés au moins une fois ?"
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  },
+  {
+   "cell_type": "code",
+   "execution_count": 32,
+   "outputs": [],
+   "source": [
+    "items_cleaned = cleanings['item_id'].unique()\n",
+    "items_delivered = deliveries['item_id'].unique()\n",
+    "items_returned = returns['item_id'].unique()\n",
+    "items_used = np.unique(np.concatenate((items_cleaned, items_delivered, items_returned)))"
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  },
+  {
+   "cell_type": "code",
+   "execution_count": 33,
+   "outputs": [
+    {
+     "name": "stdout",
+     "output_type": "stream",
+     "text": [
+      "Nombre de contenants utilisés: 40857\n"
+     ]
+    }
+   ],
+   "source": [
+    "print(\"Nombre de contenants utilisés: \" + str(len(items_used)))"
+   ],
+   "metadata": {
+    "collapsed": false
+   }
+  }
+ ],
+ "metadata": {
+  "kernelspec": {
+   "display_name": "Python 3",
+   "language": "python",
+   "name": "python3"
+  },
+  "language_info": {
+   "codemirror_mode": {
+    "name": "ipython",
+    "version": 2
+   },
+   "file_extension": ".py",
+   "mimetype": "text/x-python",
+   "name": "python",
+   "nbconvert_exporter": "python",
+   "pygments_lexer": "ipython2",
+   "version": "2.7.6"
+  }
+ },
+ "nbformat": 4,
+ "nbformat_minor": 0
+}
```

**Comment by STUTuna** [comment]
I'm using the previous version for now to get this working.
`npm install -g aicommits@1.2.0`

**Comment by mael-queau** [comment]
@edu-hilario I don't know if this is any indication of how it should perform, but trying the prompt in the playground with that diff didn't give me a length error, it worked just fine. If I'm not mistaken, the token limit should be the same there, right?

**Comment by jumang4423** [comment]
same here, @1.2.0 does work but newer is broken

**Comment by privatenumber** [comment]
I was finally able to reproduce this. Fix coming soon via https://github.com/Nutlope/aicommits/pull/147

**Comment by sebastienfi** [comment]
`1.5.0` solved this for me, try running `npm update -g aicommits`
Thanks @privatenumber
