### ISSUE TITLE
Error on ZSH

### ISSUE THREAD

**Issue by lukinhas711** [Nutlope/aicommits#140]
### Bug description

I'm trying to use aicommits but when I call the `aicommits` command in a place with git started zsh says that the command does not exist.

![image](https://user-images.githubusercontent.com/49355209/223804440-1e14f432-720d-4836-bc2f-9690e1f1af21.png)

### aicommits version

v1.3.0

### Environment

```shell
System:
OS: Windows 11 (Wsl2 Ubuntu 20.04)
CPU: Ryzen5
Shell: ZSH
Node: nvm using v16.19.0 (in this project)
Npm: v8.19.3
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by mael-queau** [comment]
Do you have these lines in your ~/.zshrc file?

```bash
source $HOME/.bash_profile
source $HOME/.bashrc
```

It has helped me solve some problems with global npm packages in the past!

**Comment by privatenumber** [comment]
Thanks for helping @mael-queau 
I'm pretty sure your analysis is correct!

FWIW I'm also using ZSH and it works fine. This is not a ZSH issue, but a Node.js global scope one.

**Comment by lukinhas711** [comment]
Thank you, it helped XD

**Comment by mael-queau** [comment]
No problem!
