### ISSUE TITLE
Too many requests error

### ISSUE THREAD

**Issue by MishaFrenkman** [Nutlope/aicommits#142]
### Bug description

I've been trying to use aicommits for weeks but always get a 429 error

```
➜  test git:(main) ✗ aicommits
┌   aicommits
│
◇  Detected 1 staged file:
     abc
│
◒  The AI is analyzing your changes
│
└  ✖ OpenAI API Error: 429 - Too Many Requests
```

I've tried to use several api keys but nothing worked.

### aicommits version

v1.3.0

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 448.98 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Your account is being rate limited:
https://help.openai.com/en/articles/6843909-rate-limits-and-429-too-many-requests-errors

**Comment by privatenumber** [comment]
Sorry, I don't know why. 🤷‍♂️ All I can do is Google the error code for you.

You'll have to open a ticket with OpenAI to find our why you're getting that error.
