### ISSUE TITLE
using aicommits in GitHub actions

### ISSUE THREAD

**Issue by MohammedAlrozzi** [Nutlope/aicommits#150]
### Feature request

This is brilliant. I love the aicommits and It describes well the changes I am making. I am running regular testing and building using GitHub action, could you please advise on how to use aicommits as part of GitHub action workflow ( before pushing)

thanks
Mo

### Why?

It just I think something like this can help in automation and is in the same direction of the ai.

**Comment by privatenumber** [comment]
Issues is reserved for bug reports and feature requests, and this sounds more like a GitHub Actions support question.

You can use aicommits on GitHub Actions just like you do on the computer. Just install and run it.

The confirmation prompt may be difficult to overcome and could be a valid use-case for https://github.com/Nutlope/aicommits/issues/61

Closing this so the conversation can happen there.
