### ISSUE TITLE
Self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by Teo230** [Nutlope/aicommits#153]
### Bug description

I modified a file (i just typed a charcater), staged the file and execute `aicommits` command and this is the result

`$ aicommits
┌   aicommits
│
◇  Detected 1 staged file:
    class.cs
│
◒  The AI is analyzing your changes
│
└  ✖ self-signed certificate in certificate chain

    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12)

    aicommits v1.5.0`

### aicommits version

v1.5.0

### Environment

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) ia32 Apple Silicon
    Memory: 4.26 GB / 11.99 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files (x86)\nodejs\node.EXE
    npm: 9.6.1 - C:\Program Files (x86)\nodejs\npm.CMD
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Looks like you're using an invalid (self-signed) certificate so Node.js is refusing to establish the connection for security reasons.

**Comment by Teo230** [comment]
I found the problem, I am using a Windows 11 VM on Parallels and the network was setted as "Shared Network". I changed it to "Bridged Network" to work. I am not sure why this happen, I use the shared network for everything, I change only when I have to communicate with iOS OS ip...someone can explain why? 🧐

**Comment by privatenumber** [comment]
Closing as it's unrelated to aicommits.

Maybe you can ask in the Parallels community.
