### ISSUE TITLE
Request timeout after 10 seconds

### ISSUE THREAD

**Issue by CasperEngl** [Nutlope/aicommits#157]
### Bug description

After updating to the latest version, the API is timing out for a lot of my commits.

Some of the larger ones used to take maybe 15-20 seconds to complete. 

A timeout of 10 seconds was added in v1.3.0 https://github.com/Nutlope/aicommits/blame/v1.3.0/src/utils/openai.ts

Is there a reason this has been added?

### aicommits version

1.5.1

### Environment

```shell
System:
  OS: macOS 12.3
  CPU: (10) arm64 Apple M1 Max
  Memory: 99.98 MB / 32.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 18.14.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /opt/homebrew/bin/yarn
  npm: 9.3.1 - /usr/local/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
There's no bug here as this is the intended experience.

10s is more than long for something like this, and you'll lose the benefits of this tool if it's taking longer (you could type your own message in that time). It also probably means there's something wrong with OpenAI's API.

Given the timing of this report, you were probably affected by the outage:
https://status.openai.com

It's probably worth linking to that page when the request times out.

**Comment by SamuelMTDavies** [comment]
> The timing was unfortunate, however, my point still stands.
> 
> I found the limit within the dist file and increased it to 100 seconds, and now my commits are running perfectly fine.

Where can I find the dist file? I've tried all over.

**Comment by privatenumber** [comment]
@CasperEngl 

I was just answering your question. But it seems you're actually requesting a feature.

If you started with a feature request to add a `timeout` config property containing milliseconds, that would be reasonable to me—PR welcome.

**Comment by CasperEngl** [comment]
My bad for adding the wrong label.
