### ISSUE TITLE
Please add support for specifying an HTTP proxy

### ISSUE THREAD

**Issue by hawkli-1994** [Nutlope/aicommits#158]
### Feature request

like:
```aicommits config set proxy="http://localhost:7890"```

### Why?

In some regions, accessing the internet requires the use of an HTTP proxy. Therefore, I request that support for specifying an HTTP proxy be added to the software. This would enable users in such regions to use the software without encountering connectivity issues.

### Alternatives

Currently, you can use the system global proxy and soft router to set the proxy.

### Additional context

![image](https://user-images.githubusercontent.com/11769524/225509899-338503b9-3440-4341-a7a6-a18314e771f1.png)

**Comment by privatenumber** [comment]
Already happening here: https://github.com/Nutlope/aicommits/pull/139

**Comment by Merry1ee** [comment]
Dear developer, not being able to use proxy is driving me crazy, please fix this ASAP, I will be very grateful ！！！🙏💗
