### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by AndreyMartinez** [Nutlope/aicommits#167]
### Bug description

this is my error 
```
 ✖ self signed certificate in certificate chain

    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)

    aicommits v1.5.1
```

### aicommits version

1.5.1

### Environment

```shell
local
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
This issue appears to be related to https://github.com/Nutlope/aicommits/issues/153.

Essentially, aicommits utilizes one of Node.js's fundamental HTTP modules to establish a connection. The error message suggests that there may be a misconfiguration in your network settings. I don't think this is related to aicommits.

**Comment by privatenumber** [comment]
Closing as it seems unrelated to aicommits, and there was no follow up.

**Comment by markolofsen** [comment]
**I switched to [`openrouter-commit`](https://www.npmjs.com/package/openrouter-commit) because it lets me choose the best AI for the job, instead of being stuck with OpenAI.**
