### ISSUE TITLE
Support GPT-4 API

### ISSUE THREAD

**Issue by privatenumber** [Nutlope/aicommits#172]
### Feature request

Support the GPT-4 API

### Why?

GPT-4 API is invite-only now, but it should be usable for those that have access.

**Comment by mvaldi** [comment]
I have GPT-4 and I would like to kindly request that you prioritize this feature, I understand that there may be competing priorities, but I genuinely believe that the ability to use GTP-4 with aicommits would be a valuable addition

**Comment by privatenumber** [comment]
You're welcome to submit a PR!

**Comment by privatenumber** [comment]
Closed via https://github.com/Nutlope/aicommits/pull/183

**Comment by markolofsen** [comment]
**[`openrouter-commit`](https://www.npmjs.com/package/openrouter-commit) > `aicommits` – supports **DeepSeek R1**, has more AI models, and is more customizable.**
