### ISSUE TITLE
Idea: 72 character limit and imperative mood

### ISSUE THREAD

**Issue by marcusziade** [Nutlope/aicommits#18]
Ensure commit titles are under the 72-character limit and that they are in the imperative mood

**Comment by privatenumber** [comment]
Not sure what you mean by imperative mood.

The 72 commit message title character limit makes sense. I'm having difficulty engineering a GPT prompt that respects it.

Example prompt:
```
Write an insightful but concise Git commit message for the following diff in present tense, without prefacing it with anything, in under 72 characters:

diff --git a/package.json b/package.json
index 2a90a5a..297f01d 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,8 @@
 	"keywords": [
 		"ai",
 		"git",
-		"commit"
+		"commit",
+		"keyword"
 	],
 	"license": "MIT",
 	"repository": "https://github.com/Nutlope/aicommits",
@@ -33,8 +34,7 @@
 		"@types/inquirer": "^9.0.3",
 		"@types/node": "^18.13.0",
 		"eslint": "^8.34.0",
-		"pkgroll": "^1.9.0",
-		"typescript": "^4.9.5"
+		"pkgroll": "^1.9.0"
 	},
 	"eslintConfig": {
 		"extends": "@pvtnbr"

```

Response: 87 characters
```
Add "keyword" to project keywords and remove "typescript" dependency from package.json.
```

**Comment by marcusziade** [comment]
@privatenumber 

Commits should be in the format where you can say:

*If I apply this commit, it will `commit message`*

Examples:

Add x
Modify x
Add 72 character limit to generator

All git commands are in the imperative mood, and so should all commits. Commits are git commands when used.

**Comment by privatenumber** [comment]
If you can engineer the prompt to phrase it imperatively, I'm open to accepting it.

**Comment by marcusziade** [comment]
It seems it already does that for the most part so that part of my idea is redundant

**Comment by Nutlope** [comment]
Seems like this was resolved, closing! Also, unfortunately GPT-3 can't keep prompts under a specific character count.
