### ISSUE TITLE
There's a 4k token limit despite being able to change the model

### ISSUE THREAD

**Issue by kanadaj** [Nutlope/aicommits#186]
### Feature request

It'd be great to either have inbuilt limits for different models, or preferably (also) support specifying the token limit in the CLI.

### Why?

GPT-4 has models that allow up to 32K models, and in the future we might get models that support even more.

**Comment by privatenumber** [comment]
You can use the model config:
https://github.com/Nutlope/aicommits#model

**Comment by privatenumber** [comment]
Ah, we forgot to remove that. Feel free to submit a PR to fix.

**Comment by rocktimsaikia** [comment]
@privatenumber Can you please release this change now since it's already merged now? This limit error comes up pretty often on large changes.

**Comment by privatenumber** [comment]
Oops, missed this. Thanks for the reminder.
