### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by vagnermaltauro** [Nutlope/aicommits#190]
### Bug description

◇  Changes analyzed
│
└  ✖ OpenAI API Error: 429 - Too Many Requests

{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}

### aicommits version

v0.0.0

### Environment

```shell
ubuntu, bash, Tilix
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by YusufcanY** [comment]
Same here!

**Comment by privatenumber** [comment]
It's an error from OpenAI, not aicommits. It tells you what's wrong:

> You exceeded your current quota, please check your plan and billing details.

**Comment by vagnermaltauro** [comment]
very strange. I still have credits. And if I'm going to use it after a long period without using the AI, it gives this error!

![image](https://user-images.githubusercontent.com/81274178/230084502-9ff10b89-1b75-462a-8789-c4bb115b9f1f.png)

**Comment by privatenumber** [comment]
It says expired April 1

**Comment by vagnermaltauro** [comment]
what the fuck!

forgive me! ;)

**Comment by Moulick** [comment]
Aka right now no one is getting any free credits at all?

**Comment by privatenumber** [comment]
Maybe you can contact OpenAI or ask on their forum?

These questions aren't relevant to aicommits so locking this thread.
