### ISSUE TITLE
Commits should be in present tense, not in past

### ISSUE THREAD

**Issue by andreisuslov** [Nutlope/aicommits#193]
### Bug description

Your description shows commits in the past tense which is not the way the git is supposed to be used

### aicommits version

latest

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 15.46 GB / 31.73 GB
Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.3 - C:\Program Files\nodejs\npm.CMD
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Not sure if there's anything we can do here.

I haven't seen past-tense messages, and the prompt says use present tense:
https://github.com/Nutlope/aicommits/blob/9b24444a2e78ddf3c9adbc3824673f6ea2a3ffa3/src/utils/openai.ts#L100
