### ISSUE TITLE
:grey_question: Question about openai free plans and ai-commits :money_with_wings: 

### ISSUE THREAD

**Issue by adriens** [Nutlope/aicommits#200]
### :information_source:  Context

Hi, we are trying to use ai-commits with an open-ai free plan, unfortunately here is what we got : 

![image](https://user-images.githubusercontent.com/5235127/234741048-24314b1f-7e08-4319-87b4-9712c4fd29ce.png)

### :grey_question: The question

:point_right: Is an openai  paid plan a prerequiste ?

**Comment by privatenumber** [comment]
IIRC Open AI doesn't have a free plan.

Perhaps your trial tokens are expired?
https://github.com/Nutlope/aicommits/issues/190#issuecomment-1497429247

**Comment by adriens** [comment]
:thinking: 

> IIRC Open AI doesn't have a free plan.

I do use tokens ... but never paid, I got them from here : https://platform.openai.com/account/api-keys


![image](https://user-images.githubusercontent.com/5235127/234994808-8c932d67-fc62-4d8b-aaac-a2edf50350a8.png)


You mean these may not work with ai-commits.. while still allowing me to call api (see my [Kaggle 🪄 OpenAI - Gender guess on firstname](https://www.kaggle.com/code/adriensales/openai-gender-guess-on-firstname)) ?

**Comment by adriens** [comment]
If it can help, find the code that actually works below : 

```python
!pip install openai

import openai
from kaggle_secrets import UserSecretsClient

user_secrets = UserSecretsClient()
openai.api_key = user_secrets.get_secret("OPENAI_API_KEY")

def guess_genre(fname):
    genre = 'MASCULIN'
    #"""
    response = openai.Completion.create(
      model = "text-davinci-003",
      prompt = "Extract the genre of the given firstname. If a MAN, reply <MASCULIN>, if a woman, reply <FEMININ>, else reply <NOT_GUESSED>. firstname :" +
            fname,
      temperature=0,
      max_tokens=64,
      top_p=1.0,
      frequency_penalty=0.0,
      presence_penalty=0.0
    )
    genre = response["choices"][0]["text"].strip()
    #"""
    # print(response)
    # print("Guessed Genre : <" + genre + ">", sep = '')
    
    return genre
```

**Comment by privatenumber** [comment]
Maybe it has something to do with the type of free tokens you use.

You can try experimenting to see if `gpt-3.5-turbo` works here:
https://platform.openai.com/playground?mode=chat

Or maybe you're using `gpt-4` but you don't have access yet?

**Comment by adriens** [comment]
> Or maybe you're using gpt-4 but you don't have access yet?

Exact :heavy_heart_exclamation: 


> You can try experimenting to see if gpt-3.5-turbo works here:
https://platform.openai.com/playground?mode=chat

Yup, I'm indeed using `gpt-3.5-turbo` : I guess it can be customized in ai-commit ?

**Comment by adriens** [comment]
:pray: Thanks for the feedback.

:point_right: I'll let you know if we managed to make it work on `gpt-3-5` :crossed_fingers:
