### ISSUE TITLE
document how to generate conventional commits

### ISSUE THREAD

**Issue by AllanOricil** [Nutlope/aicommits#213]
### Feature request

lots of projects are now using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) conventions. It would be nice if this cli could generate commit message following this patttern

````bash
<type>[optional scope]: <description>
````

rules: https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js

projects can also overwrite these rules...

Maybe if you provide the resolved set of rules, the AI becomes aware of the context and it starts to generate commits following the patterns described in the json.

### Why?

does not support https://www.conventionalcommits.org/en/v1.0.0/

### Alternatives

N/a

### Additional context

N/a

**Comment by privatenumber** [comment]
You can with: https://github.com/Nutlope/aicommits/releases/tag/v1.11.0

Guess we missed updating the docs @ThijSlim
