### ISSUE TITLE
Models other than gpt-3.5-turbo result in fault

### ISSUE THREAD

**Issue by rabayliss** [Nutlope/aicommits#224]
### Bug description

Toggling the model for gpt-4, or 3, or any variant thereof in PyCharm  gives the error:
"the model <> does not exist"

### aicommits version

2.2.1

### Environment

```shell
Windows 10 2023.1.2
Pycharm: PC-231.9011.38
Version 2023.1.2 
PyCharm 2023.1.2 (Community Edition)
Build #PC-231.9011.38, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
    ide.balloon.shadow.size=0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
PyCharm? Is this the right project?

**Comment by rabayliss** [comment]
Perhaps not? Please close this issue.
