### ISSUE TITLE
All commit messages are in present

### ISSUE THREAD

**Issue by mickaelxd** [Nutlope/aicommits#231]
### Bug description

Hi, my name is Mickael and I'm a Brazilian developer. I use aicommits with the locale pt. Every commit I generate comes in the present tense, so instead of "Added button on order screen" it says "Add button on order screen", is this a normal behavior?

### aicommits version

1.11.0

### Environment

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 72.95 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.custom-node/node16/bin/node
    Yarn: 1.22.17 - ~/.custom-node/node16/bin/yarn
    npm: 8.1.2 - ~/.custom-node/node16/bin/npm
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment]
Yes, it follows the imperative style commit message:
https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages
