### ISSUE TITLE
Allow the commit message to be edited

### ISSUE THREAD

**Issue by spenserblack** [Nutlope/aicommits#24]
This is an awesome tool!

A lot of times, AI comes up with something that is *mostly* good, but may need one or two small corrections. It might be handy to take `E` for edit when prompted to use the commit message. What this could do is write the message to a file like `.git/AICOMMITS_EDITMSG`, then call `git commit -eF .git/AICOMMITS_EDITMSG` to open the AI-generated message in the user's editor and let them change it before committing.

As a workaround, the user can say "Yes" when asked to use the commit message, and then call `git commit --amend` to make some small adjustments. But the AI-generated commit message might not pass any git hooks that check the message's contents this way.

Happy to submit a PR if this sounds good.

**Comment by Nutlope** [comment]
Thanks for the suggestion @spenserblack, I agreed that this would be great! @privatenumber has a PR #64 that when merged, should enable us to do this well. I'll let you two chat about implementation details :)

**Comment by privatenumber** [comment]
I'm working on a Git hook in #83 so using the editor configured in Git will open via `git commit` with AI generated messages.

For CLI mode, @Nutlope wants a more user-friendly editor inline.

**Comment by spenserblack** [comment]
A git hook is an interesting idea :+1:

Assuming that a user would want to use aicommits in *all* repositories via the hook, I wonder if it would make sense to document how to use a [template directory](https://git-scm.com/docs/git-init#_template_directory) so that all new repos come with the hook pre-installed.

**Comment by privatenumber** [comment]
Closed via #95

**Comment by joeytwiddle** [comment]
This makes it possible to edit when using the hook integration.

But I think it would still be useful to hit `E` to edit the commit, when using the `aicommits` command on an un-hooked project.

Why? I jump around lots of projects, and occasionally call on `aicommits`. I would like to have this feature without needing to set up the hook integration.

**Comment by privatenumber** [comment]
That idea was tabled because we'll need to maintain a CLI text editor which would be a huge maintenance risk if people keep asking for more features.

**Comment by spenserblack** [comment]
>we'll need to maintain a CLI text editor

Can't you just start a text editor subprocess? Git picks the editor to use in this order:

1. `$GIT_EDITOR`
2. core.editor config value
3. `$VISUAL`
4. `$EDITOR`

E.g. `GIT_EDITOR=vi git commit`.

So instead of building out a CLI text editor, why not try to resolve an editor from these and try to execute them in a subprocess?

**Comment by privatenumber** [comment]
That's what was implemented with the git hook.

**Comment by spenserblack** [comment]
I agree with the implication in @joeytwiddle's comment that installing a hook in many repositories can get repetitive. TBH I usually limit hooks to what *must* be used to contribute to a repo (linters, formatters, etc.).

Maybe I'm misunderstanding your definition of "CLI text editor," but what I'm asking is if `E` should remain tabled if you *don't* need to maintain a CLI text editor.

**Comment by joeytwiddle** [comment]
Instead of aicommits opening an editor, perhaps we could ask git to go it.

For example, after running `git commit -m ...`

https://github.com/Nutlope/aicommits/blob/578572b1d9a28f3e568314f6bb67a37276266e2f/src/commands/aicommits.ts#L101

We could immediately run `git commit --amend`

(iff the user had pressed `E`)
