### ISSUE TITLE
Customize generated commit message

### ISSUE THREAD

**Issue by ekalchev** [Nutlope/aicommits#267]
### Feature request

We have custom commit message pattern build on top of conventional commits. Please tell me where in the code I can add instructions to the AI service to append some additional information for the first line of the commit message. I would do it myself, I just need direction where is the right place in the code to add this.

### Why?

We have custom commit message pattern

**Comment by guidomodarelli** [comment]
You can edit here
https://github.com/Nutlope/aicommits/blob/604def8284361b8827087350fe6fcb6d9e2de836/src/utils/prompt.ts#L21-L35
