### ISSUE TITLE
Error: error: pathspec 'World log statement' did not match any file(s) known to git

### ISSUE THREAD

**Issue by ziarparvaiz** [Nutlope/aicommits#28]
i git init on an existing project
git add .
then run aicommits
@Nutlope 
![Screenshot_3](https://user-images.githubusercontent.com/50423368/218868949-a622442d-4feb-4cfa-8e41-78dd71ecf76b.png)

**Comment by privatenumber** [comment]
This should be fixed in https://github.com/Nutlope/aicommits/releases/tag/v1.0.7 where we escape the message
