### ISSUE TITLE
Add support for conventional commits

### ISSUE THREAD

**Issue by SuuSoJeat** [Nutlope/aicommits#32]
It would be nice if there is an option to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by andreacavagna01** [comment]
+1

**Comment by Nutlope** [comment]
This is a top priority feature that's currently in the README. We'll try to prioritize it and release it soon!

**Comment by guanguans** [comment]
Share my repository([https://github.com/guanguans/ai-commit](https://github.com/guanguans/ai-commit)) written in PHP.
Support to generate multiple conventional messages for us to choose.

**Comment by warengonzaga** [comment]
This is must be added as a feature.

**Comment by thijslimmen** [comment]
I created the following PR to enable conventional commits as configuration: 
https://github.com/Nutlope/aicommits/pull/160

**Comment by kwiss** [comment]
conventional commits is a must have +1 let's go for the prompt addition of @thijslimmen

**Comment by vanarok** [comment]
Such a simple function and such a long implementation.

**Comment by ThijSlim** [comment]
#177 is the implementation and it takes a while for it be merged, which is sad 😕

**Comment by Braunson** [comment]
Even the functionality to specify a "prefix" to prefix the commit message would be a quick one..  i.e. `aitcommit -p "chore:"`

**Comment by privatenumber** [comment]
Closed via #177
