### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by erikpeik** [Nutlope/aicommits#43]
Hey,

Is there coming support for Windows or how I export that env in windows? :D

**Comment by iamshabell** [comment]
Yes, it supports the Windows operating system.

To set an environment variable,  you can use the System Properties dialog, Here's how:
- Open the Start menu and search for  "Environment Variables".
- Click on "Edit the system environment variables".
- Click on the "Environment Variables" button.
- In the "User variables" section, click the "New" button.
- Enter the name `OPENAI_KEY` and value(your OpenAI API key) `sk-xxxxxxxxxxxxxx` for the environment variable.
- Click "OK" to close all the windows.

Note that you will need to open a new command prompt or restart any programs that you want to use the environment variable in for the changes to take effect.

To verify that the environment variable has been set, you can use the echo command: 
```bash
echo %OPENAI_KEY%
```
it should output your OpenAPI key `sk-xxxxxxxxxxxxxx`

If you encounter any issues, please let us know by submitting a problem report.

**Comment by erikpeik** [comment]
Thanks, a lot! I had already done those steps but had a typo in my variable name. 

Works now! :)
