### ISSUE TITLE
Support for regenerate commit messsage

### ISSUE THREAD

**Issue by ugurcemozturk** [Nutlope/aicommits#46]
Re-generation of the commit message requires declining and re-running the tool.
An extra cli flag can be added along with `yes/no`. 

Proposed output:
```
Would you like to use this commit message? (Y / n / r)
```

Thanks a lot for your great work.

**Comment by iamshabell** [comment]
Wonderful idea! It could streamline the procedure and lead to time savings. I would be interested in submitting a PR for that.

**Comment by ugurcemozturk** [comment]
It can be even combined with another proposal I saw in issues. There can be another flag to edit the commit message. so the final prompt may look like

```
Would you like to use this commit message? (Y(yes) / n(no) / r(retry)/ e(edit))
```

**Comment by Nutlope** [comment]
Agreed that this would be great! It's a duplicate of #24 where we're tracking it so closing this one for now.
