### ISSUE TITLE
OpenAI API Error

### ISSUE THREAD

**Issue by ribeiroevandro** [Nutlope/aicommits#49]
Anyone else with this problem? Is there any way for me to know if the problem is in the OpenAI API or if it is some configuration of my machine?

<img width="608" alt="Screenshot 2023-02-15 at 21 51 40" src="https://user-images.githubusercontent.com/943553/219230070-4f296e78-9cb0-4a57-aaee-8a3735b3d39a.png">

**Comment by privatenumber** [comment]
It's from OpenAI.

I get it a lot too and I can understand since everyone is using them these days but you can try opening a ticket with them.
