### ISSUE TITLE
Commits and Periods

### ISSUE THREAD

**Issue by macjabeth** [Nutlope/aicommits#66]
Awesome tool by the way!

I noticed that it automatically adds a period to the end of the commit message.

It is generally accepted that Git commit subject lines should not be ended with a period, just like email subject lines. This is particularly important to remember because of the 50 character limit, as every character counts.

I suggest a small change to the code that strips any period from the end should it exist.

**Comment by Nutlope** [comment]
Agreed, this was just fixed in #59!
