### ISSUE TITLE
Error: Command failed: in Windows Powershell 

### ISSUE THREAD

**Issue by yusefren** [Nutlope/aicommits#7]
Error while executing in windows.
```
fatal: ':(exclude)package-lock.json': no such path in the working tree.
Use 'git <command> -- <path>...' to specify paths that do not exist locally.
node:internal/errors:863
  const err = new Error(message);
              ^

Error: Command failed: git diff --cached . ':(exclude)package-lock.json' ':(exclude)yarn.lock'
fatal: ':(exclude)package-lock.json': no such path in the working tree.
Use 'git <command> -- <path>...' to specify paths that do not exist locally.
```

This is because https://github.com/Nutlope/aicommits/blob/b48683755b0a43e35ce1eeeba69c37d83fc33ab0/aicommits.ts#L31
Windows does not like single quote in `execSync`

I will create a PR soon

**Comment by Nutlope** [comment]
@yusefren Great catch, would very much welcome a PR! I didn't test it on Windows so this is great info. Thank you!

**Comment by Nutlope** [comment]
Closing since this is now fixed!
