### ISSUE TITLE
Is `aicommits` using `aicommits`?

### ISSUE THREAD

**Issue by orhun** [Nutlope/aicommits#78]
I was just wondering if the commits in this project are written by `aicommits` 🌝

**Comment by privatenumber** [comment]
Sometimes within PRs, but for squash-merging to `main`, I follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) so releases/changelog can be automated.

**Comment by orhun** [comment]
Ooh, got it. Btw if you're interested in utilizing conventional commits for the changelog, you can check out https://github.com/orhun/git-cliff
