### ISSUE TITLE
I don't understand how to set the key 

### ISSUE THREAD

**Issue by gans92** [Nutlope/aicommits#79]
![Screenshot_338](https://user-images.githubusercontent.com/96514967/219903288-323cf4ec-7492-47ad-a60f-86e4e5968fde.png)

**Comment by privatenumber** [comment]
It's in Step 3 here: https://github.com/Nutlope/aicommits#installation-and-usage

We'll add a config command soon so it's easier to set this up.

**Comment by gans92** [comment]
"echo "OPENAI_KEY=<your token>" >> ~/.aicommits"

this command inside the folder where the aicommits is this or in the project itself?, I tried both but it didn't work

**Comment by privatenumber** [comment]
Did you insert your API token where it says `<your token>`?

**Comment by gans92** [comment]
yes

**Comment by coSevenSeven** [comment]
![image](https://user-images.githubusercontent.com/108878201/220241585-4dc6c5c8-a0ff-4c71-8cb5-386522149c52.png)
got same problem which .aicommits is already set

**Comment by privatenumber** [comment]
Will add Windows test

**Comment by AntoineKM** [comment]
Hey @gans92 and @coSevenSeven you might check this issue here: #67

**Comment by coSevenSeven** [comment]
> Hey @gans92 and @coSevenSeven you might check this issue here: #67

it works well, thanks! 👍

**Comment by gans92** [comment]
> Hey @gans92 and @coSevenSeven you might check this issue here: #67

thanks, I created the file manually with vscode and now everything is working.

**Comment by tooilxui** [comment]
I use aicommits in wsl, and aicommits config not work too, an other way to fix it, is export OPENAI_KEY=yor_key.

**Comment by privatenumber** [comment]
Sorry, we haven't actually released the `aicommits config` command.

**Comment by privatenumber** [comment]
Released in https://github.com/Nutlope/aicommits/releases/tag/v1.2.0
