### ISSUE TITLE
support commitlint

### ISSUE THREAD

**Issue by Manonicu** [Nutlope/aicommits#8]
⧗   input: Commit message: Add 3D card style module and modifications to 3D card component
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)
node:internal/errors:867
  const err = new Error(message);

**Comment by Nutlope** [comment]
I'll look into supporting this when I add support for conventional hooks. Thanks for reporting!

**Comment by Nutlope** [comment]
Closing this for now since it's on the feature list in the README

**Comment by iandjx** [comment]
i just created a simple update to allow commitlint and published it in npm as @iandjx/aicommits

https://github.com/iandjx/aicommits/tree/commitlint
