### ISSUE TITLE
Add installation using Homebrew

### ISSUE THREAD

**Issue by thedrow** [Nutlope/aicommits#82]
It's easier to manage CLI updates with Homebrew, you don't have to install NodeJS yourself and it's generally the best practice to allow the installation of CLI tools with Homebrew.
Please contribute a formula to the homebrew repository or create your own tap.

**Comment by mogeko** [comment]
I tried to submit an PR to [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core). 

But I got stuck in the audit step:

```shell
$ brew audit --new aicommits
aicommits:
  * GitHub repository too new (<30 days old)
Error: 1 problem in 1 formula detected
```

Maybe we should wait until this project is more stable before trying to make a Homebrew Formula.

**Comment by pavelzw** [comment]
[homebrew/homebrew-core#125882](https://github.com/Homebrew/homebrew-core/pull/125882) fixes this issue.

**Comment by mogeko** [comment]
> [homebrew/homebrew-core#125882](https://github.com/Homebrew/homebrew-core/pull/125882) fixes this issue.

that's right.
