### ISSUE TITLE
The diff is too large for the OpenAI API

### ISSUE THREAD

**Issue by mrdulin** [Nutlope/aicommits#90]
```bash
⚡  aicommits
┌   aicommits 
│
○  Detected 5 staged files:
     src/pages/toutiao/pages/article/hooks.ts
     src/pages/toutiao/pages/article/index.tsx
     src/pages/toutiao/pages/disease/index.tsx
     src/pages/toutiao/route.ts
     src/pages/toutiao/types.ts
│
○  The AI is analyzing your changes
│
└  ✖ The diff is too large for the OpenAI API
```

What happened?

**Comment by privatenumber** [comment]
It says what happened in the error message and your title. Is there something more specific you want to ask?

**Comment by mrdulin** [comment]
@privatenumber When this error happens, it prevents the commit. How can I solve it?

**Comment by privatenumber** [comment]
The tool can't send the diff to the server so not much. You can either write your own message or unstage some files to make smaller commits.

As an action item, we should log these options.
