### ISSUE TITLE
Support control commit message length

### ISSUE THREAD

**Issue by mysteryven** [Nutlope/aicommits#91]
Since I run `aicommit` in my terminal, I get the message below:

```text
Update PRINT opcode to join stack items with a space and print on a single line.
```

It save me time about thinking message, I love it, but I want to add `refactor` prefix, so I copy this message and fill the message in the commit box of VSCode, but the VSCode errors me "40 characters over 50 in current line".

<img width="316" alt="CleanShot 2023-02-21 at 11 26 37@2x" src="https://user-images.githubusercontent.com/33973865/220239948-8333c0b9-403a-424e-b9de-65b6a4c7448f.png">

Could it support control commit message's length?

**Comment by rocktimsaikia** [comment]
@privatenumber This can be closed now as the change is merged now.

**Comment by privatenumber** [comment]
Closed via https://github.com/Nutlope/aicommits/pull/194
