### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME when using aicommits

### ISSUE THREAD

**Issue by hamzaafridi** [Nutlope/aicommits#93]
I am trying to use aicommits for the first time but it's returning this:
```
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
```

node version: 14.4
platform: debian 10

any help here would be highly appreciated. 
Thanks

**Comment by privatenumber** [comment]
Node v14.4 was released almost 3 years ago and is outdated.

Please update to to v14 LTS.
