### ISSUE TITLE
Cannot read property 'statusText' of undefined

### ISSUE THREAD

**Issue by careteenL** [Nutlope/aicommits#97]
Running `aicommits` command when `getaddrinfo ENOTFOUND api.openai.com` will raise an error `Cannot read property 'statusText' of undefined`

**Comment by privatenumber** [comment]
Sounds like you're not able to connect to [api.openai.com](https://api.openai.com). Can you confirm?

As an action item, we should add better error messages for this.

**Comment by privatenumber** [comment]
Closed via #100
